name: Build and Test Go Project
on:
  push:
    branches:
      - develop_manas
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Set Environment Variables
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: echo "Environment variable MY_ENV_VAR is set to $MY_ENV_VAR"

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: go run cmd/main.go